memcached:
  image: memcached
db:
  image: mysql
  volumes:
    - /dev/log:/dev/log
    - ./data/mysql/runtime:/var/lib/mysql
    - ./data/mysql/dump:/dump
  env_file:
    - ./env
  environment:
    MYSQL_DATABASE: vimbadmin
    MYSQL_USER: vimbadmin
postfix:
  image: indiehosters/postfix
  hostname: "$HOST"
  links:
    - db
  volumes_from:
    - dovecot 
  volumes: 
    - ./data/postfix/data:/data
    - ./data/postfix/mail:/var/mail 
    - ./opendkim:/etc/opendkim
    - ./TLS:/ssl 
    - /dev/log:/dev/log
  ports:
    - "25:25"
    - "587:587"
dovecot:
  image: indiehosters/dovecot
  links:
    - db
  volumes:
    - ./data/dovecot/mail:/mail
    - ./TLS:/ssl
    - /dev/log:/dev/log
  ports:
    - "993:993"
vimbadmin:
  image: indiehosters/vimbadmin
  hostname: "$HOST"
  links:
    - db
    - memcached
    - postfix
  volumes_from:
    - dovecot 
  volumes:
    - ./salts:/salts
  env_file:
    - ./env
  environment:
    APPLICATION_ENV: production
web:
  image: nginx
  hostname: "$HOST"
  links:
    - vimbadmin
  volumes_from:
    - vimbadmin
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  environment:
    - HOST
