memcached:
  image: memcached
db:
  image: mysql
  volumes:
    - /dev/log:/dev/log
    - ./data/mysql/runtime:/var/lib/mysql
    - ./data/mysql/dump:/dump
  env_file:
    - ./env
  environment:
    MYSQL_DATABASE: vimbadmin
    MYSQL_USER: vimbadmin
spamassassin:
    image: indiehosters/spamassassin
    links:
      - dovecot
    volumes:
      - /dev/log:/dev/log
postfix:
  image: indiehosters/postfix
  hostname: "$HOST"
  links:
    - db
    - spamassassin
    - dovecot
  volumes: 
    - ./opendkim:/etc/opendkim
    - ./TLS:/ssl 
    - /dev/log:/dev/log
  ports:
    - "25:25"
    - "587:587"
dovecot:
  image: indiehosters/dovecot
  links:
    - db
  volumes:
    - ./data/dovecot/mail:/mail
    - ./TLS:/ssl
    - /dev/log:/dev/log
  ports:
    - "993:993"
    - "995:995"
vimbadmin:
  image: indiehosters/vimbadmin
  hostname: "$HOST"
  links:
    - db
    - memcached
    - postfix
  volumes_from:
    - dovecot 
  volumes:
    - ./salts:/salts
    - ./indie.signed.mobileconfig:/var/www/html/public/indie.signed.mobileconfig
  env_file:
    - ./env
  environment:
    APPLICATION_ENV: production
    CLOUD_HOST
web:
  image: nginx
  hostname: "$HOST"
  links:
    - vimbadmin
  volumes_from:
    - vimbadmin
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  environment:
    - HOST
    - AUTOCONFIG_HOST="$HOST"
